# Generated by Django 5.2.8 on 2026-02-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='staff_id',
            field=models.CharField(error_messages={'unique': 'An instructor with that staff id already exists.'}, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(error_messages={'unique': 'A student with that student number already exists.'}, max_length=10, unique=True),
        ),
    ]
