# Generated by Django 5.1.3 on 2024-12-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('condition', models.FloatField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.instructor')),
            ],
        ),
    ]
