# Generated by Django 5.1.3 on 2024-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='condition',
            field=models.TextField(null=True),
        ),
    ]
