# Generated by Django 5.2.8 on 2026-02-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_head_ta'),
        ('request', '0002_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='head_TA',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='request.request'),
        ),
    ]
