# Generated by Django 5.2.8 on 2026-02-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_condition_alter_course_head_ta'),
        ('faculty', '0003_alter_instructor_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='condition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.instructor'),
        ),
    ]
